/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE_ADDR 					0x40023800UL
#define RCC_CFGR_REG_OFFSET 			0x08UL
#define RCC_CFGR_REG_ADDR				( RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET)

#define RCC_AHB1ENR_REG_OFFSET			0x30UL
#define RCC_AHB1ENR_REG_ADDR			(RCC_BASE_ADDR + RCC_AHB1ENR_REG_OFFSET)

#define GPIOA_BASE_ADDR					0x40020000UL
#define GPIOA_MODER_REG_OFFSET			0x00UL
#define GPIOA_MODER_REG_ADDR			(GPIOA_BASE_ADDR + GPIOA_MODER_REG_OFFSET)

#define GPIOA_AFRH_REG_OFFSET			0x24UL
#define GPIOA_AFRH_REG_ADDR				(GPIOA_BASE_ADDR + GPIOA_AFRH_REG_OFFSET)

int main(void)
{
	uint32_t *pRccCfgrReg =  (uint32_t*) RCC_CFGR_REG_ADDR;


	//1. Configure the RCC_CFGR MCO1 bit fields to select HSI as clock source
	*pRccCfgrReg &= ~(0x3 << 21); //clear 21 and 22 bit positions

	//Configure MCO1 prescaler
	/* add a prescalar value before reading MCO1 */
	*pRccCfgrReg 	|= (1<< 25);
	*pRccCfgrReg	|= (1<< 26);

	//2. Configure PA8 to AF0 mode to behave as MCO1 signal
	uint32_t *pRccAhb1enr =  (uint32_t*) RCC_AHB1ENR_REG_ADDR;

	//a ) Enable the peripheral clock for GPIOA peripheral
	/*enable RCC AHB1 peripheral clock register which is used by GPIOA */
	*pRccAhb1enr |=(1<<0);

	//b) Configure the mode of GPIOA pin 8 as alternate function mode
	uint32_t *pGPIOAModerReg = (uint32_t*) GPIOA_MODER_REG_ADDR;
	*pGPIOAModerReg &= ~ (0x3 << 16); //clear
	*pGPIOAModerReg  |=  (0x2 << 16);//set

	//c) Configure the alternation function register to set the mode 0 for PA8
	uint32_t *GPIOAAltFunHighReg = (uint32_t*) GPIOA_AFRH_REG_ADDR;
	*GPIOAAltFunHighReg &= ~(0xf<<0);//clear

    /* Loop forever */
	for(;;);
}
